# DigitalOcean App Platform configuration for rbAI
# This file defines all components for deployment

name: rbai-app
region: sgp

# Database
databases:
  - name: db
    engine: PG
    version: "15"
    size: basic
    num_nodes: 1
    production: false

# Backend Service
services:
  - name: rbai-backend
    source:
      repo: https://github.com/auxghlann/rbAI
      branch: main
    source_dir: rbAI_backend
    
    github:
      deploy_on_push: true
    
    build_command: pip install -e .
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    health_check:
      http_path: /health
      initial_delay_seconds: 10
    
    envs:
      - key: GROQ_API_KEY
        scope: RUN_TIME
        value: "your-groq-api-key-here"
      
      - key: SECRET_KEY
        scope: RUN_TIME
        value: "generate-with-openssl-rand-hex-32"
      
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${rbai-frontend.PUBLIC_URL}
      
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      
      # Uncomment after deploying execution droplet
      # - key: EXECUTION_SERVICE_URL
      #   scope: RUN_TIME
      #   value: "http://YOUR_DROPLET_IP:8080"
      
      # - key: EXECUTION_API_KEY
      #   scope: RUN_TIME
      #   value: "your-execution-api-key"

# Frontend Static Site
static_sites:
  - name: rbai-frontend
    source:
      repo: https://github.com/auxghlann/rbAI
      branch: main
    source_dir: rbAI_frontend
    
    github:
      deploy_on_push: true
    
    build_command: npm run build
    output_dir: dist
    
    routes:
      - path: /
    
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${rbai-backend.PUBLIC_URL}
      
      - key: NODE_VERSION
        scope: BUILD_TIME
        value: "18"
